<?php
$itemMedia = $item->media();

$this->headLink()->appendStylesheet($this->assetUrl('css/mirador-combined.css'));

$this->headScript()->appendFile($this->assetUrl('js/mirador.js', 'Mirador'));

function console_log( $data ){
  echo '<script>';
  echo 'console.log('. json_encode( $data ) .')';
  echo '</script>';
}

// console_log($items);

$manifest_url = $this->iiifUrl($item) ;
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" type="text/css" href="/modules/Mirador/asset/css/mirador-combined.css">
    <title>Mirador Viewer</title>

        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    <style type="text/css">
     #viewer {
       width: 100%;
       height: 100%;
       position: fixed;
     }
    </style>
  </head>
  <body>
    <div id="viewer"></div>

    <script type="text/javascript">

     $(function() {
       myMiradorInstance = Mirador({
         "id": "viewer",
         "layout": "1x1",
         "buildPath": "",
         "i18nPath": "/modules/Mirador/asset/locales/",
         "imagesPath" : '/modules/Mirador/asset/images/',
         "data": [
        <?php foreach ($items as $itemSetItem): ?>
          <?php $itemSetItemManifest = $this->iiifUrl($itemSetItem); ?>
           { "manifestUri": "<?php echo $itemSetItemManifest; ?>", "location": "SlaveryImages.org" },
        <?php endforeach; ?>
           { "manifestUri": "<?php echo $manifest_url; ?>", "location": "SlaveryImages.org" }
         ],
         "windowObjects": [{
           loadedManifest: "<?php echo $manifest_url; ?>",
           viewType: "ImageView"
         }],
         'windowSettings' : {
           "canvasControls": { // The types of controls available to be displayed on a canvas
             "annotations" : {
               "annotationLayer" : false, //whether or not to make annotation layer available in this window
             },
             "imageManipulation" : {
               "manipulationLayer" : true
             }
           }
         }
       });
     });
    </script>
  </body>
</html>





<?php $this->trigger('view.show.after'); ?>