
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" type="text/css" href="/modules/build/mirador/css/mirador-combined.min.css">
    <title>Mirador Viewer</title>
    <style type="text/css">
     #viewer {
       width: 100%;
       height: 100%;
       position: fixed;
     }
    </style>
  </head>
  <body>
    <div id="viewer"></div>

    <?php
      $demo_mirador_url = "http://projectmirador.org/demo/mirador.min.js";
      $local_mirador_url = "/modules/build/mirador/mirador.min.js";
      $local_mirador_nonmin_url = "/modules/build/mirador/mirador.js";
      $yale_mirador_url = "http://mirador.britishart.yale.edu/build/mirador/mirador.js";
    ?>

    <script src="<?php echo $local_mirador_nonmin_url; ?>"></script>

    <?php 
        $manifest_url = $this->iiifUrl($item) ;

        $itemSets = $item->itemSets();
        foreach ($itemSets as $itemSet):
        	$manifestList = array();
        	foreach ($itemSet->items() as $setItem):
        		array_push($manifestList, $this->iiifUrl($setItem));
        	endforeach;
     	endforeach;
    ?>
 
    <script type="text/javascript">

     $(function() {
       myMiradorInstance = Mirador({
         "id": "viewer",
         "layout": "1x1",
         "data": [
           <?php foreach ($manifestList as $manifest): ?>           	
           { "manifestUri": "<?php echo $manifest ?>", "location": "SlaveryImages.org"},
           <?php endforeach; ?>
           { "manifestUri": "<?php echo $manifest_url ?>", "location": "SlaveryImages.org"},
         ],
         "windowObjects": [{
           loadedManifest: "<?php echo $manifest_url ?>", "location": "SlaveryImages.org",
           viewType: "ImageView",
         }],
         "annotationEndpoint": { "name":"Local Storage", "module": "LocalStorageEndpoint" },
         "windowSettings": {
           "canvasControls": { // The types of controls available to be displayed on a canvas
             "imageManipulation" : {
               "manipulationLayer" : true,
               "controls" : {
                 "mirror" : true
               }
             }
           }
         }
       });
     });
    </script>

  </body>
</html>
