<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
// $embedMedia = $this->siteSetting('item_media_embed', false);
$embedMedia = false;
$itemMedia = $item->media();


function console_log( $data ){
  echo '<script>';
  echo 'console.log('. json_encode( $data ) .')';
  echo '</script>';
}

//console_log($itemMedia);

$manifest_url = $this->iiifUrl($item) ;
$mirador_url = "http://mirador.britishart.yale.edu/?manifest=$manifest_url";

?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" type="text/css" href="http://mirador.britishart.yale.edu/build/mirador/css/mirador-combined.css">
    <title>Mirador Viewer</title>
    <style type="text/css">
     #viewer {
       width: 100%;
       height: 100%;
       position: fixed;
     }
    </style>
  </head>
  <body>
    <div id="viewer"></div>

    <script src="http://mirador.britishart.yale.edu/build/mirador/mirador.js"></script>
    <script type="text/javascript">

     $(function() {
       myMiradorInstance = Mirador({
         "id": "viewer",
         "layout": "1x1",
         "buildPath": "",
         "data": [
           { "manifestUri": "<?php echo $manifest_url; ?>", "location": "SlaveryImages.org" }
         ],
         "windowObjects": [{
           loadedManifest: "<?php echo $manifest_url; ?>",
           viewType: "ImageView"
         }],
         "annotationEndpoint": { "name":"Local Storage", "module": "LocalStorageEndpoint" },
         "windowSettings": {
           "canvasControls": { // The types of controls available to be displayed on a canvas
             "imageManipulation" : {
               "manipulationLayer" : true,
               "controls" : {
                 "mirror" : true
               }
             }
           }
         }
       });
     });
    </script>
  </body>
</html>





<?php $this->trigger('view.show.after'); ?>